# Generated by Django 3.0.4 on 2020-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_number', models.CharField(max_length=20, null=True)),
                ('cod_number', models.CharField(db_index=True, default=None, max_length=20)),
                ('ware', models.CharField(max_length=6)),
                ('reason', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'adjusttable',
            },
        ),
        migrations.CreateModel(
            name='AttributeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='物料代码')),
                ('name', models.CharField(max_length=50, verbose_name='物料名称')),
                ('type', models.CharField(max_length=4, verbose_name='类型')),
                ('unit', models.CharField(max_length=3, null=True, verbose_name='单位')),
                ('pur_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购价')),
                ('pla_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划价')),
                ('mat_group', models.CharField(max_length=6, verbose_name='物料组')),
                ('dra_number', models.CharField(max_length=20, null=True, verbose_name='图号')),
                ('profession', models.CharField(max_length=2, null=True, verbose_name='专业')),
                ('virtual', models.CharField(max_length=4, null=True, verbose_name='虚拟')),
                ('description', models.CharField(max_length=20, null=True, verbose_name='说明')),
            ],
            options={
                'db_table': 'attributetable',
            },
        ),
        migrations.CreateModel(
            name='CostprojectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=6)),
                ('pro_name', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('month', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
            options={
                'db_table': 'CostprojectTable',
            },
        ),
        migrations.CreateModel(
            name='DispatchTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_number', models.CharField(default=None, max_length=20)),
                ('date', models.DateField()),
                ('ord_number', models.CharField(max_length=20, null=True)),
                ('sfc_ware', models.CharField(max_length=6)),
                ('out_ware', models.CharField(db_index=True, max_length=6)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'dispatchtable',
            },
        ),
        migrations.CreateModel(
            name='EntruSumTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cod_number', models.CharField(db_index=True, default=None, max_length=20)),
                ('entru_number', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'entrusumtable',
            },
        ),
        migrations.CreateModel(
            name='IncomeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_number', models.CharField(db_index=True, default=None, max_length=20)),
                ('date', models.DateField()),
                ('ord_number', models.CharField(max_length=20, null=True)),
                ('ware', models.CharField(max_length=6)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'db_table': 'incometable',
            },
        ),
        migrations.CreateModel(
            name='SalePriceTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_number', models.CharField(db_index=True, default=None, max_length=20)),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('not_tax_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bnot_tax_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'salepricetb',
            },
        ),
        migrations.CreateModel(
            name='ScrappedToOutputTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=6)),
                ('ware', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('ware2', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('ware_a', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('reason', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'scrappedtooutputtable',
            },
        ),
        migrations.CreateModel(
            name='TransferTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_number', models.CharField(max_length=20, null=True)),
                ('cod_number', models.CharField(db_index=True, default=None, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('out_ware', models.CharField(max_length=6)),
                ('in_ware', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'transfertable',
            },
        ),
    ]
