# Generated by Django 3.0.4 on 2020-12-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuclearPriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version1', models.CharField(max_length=20)),
                ('version2', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('cod_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='物料代码')),
                ('name', models.CharField(max_length=50, verbose_name='物料名称')),
                ('pac_price1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='套餐价1')),
                ('pac_price2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='套餐价2')),
                ('gua_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保本价')),
                ('point1', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='点位1')),
                ('point2', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='点位2')),
            ],
            options={
                'db_table': 'NuclearPriceTable',
            },
        ),
    ]
